# Generated by Django 4.2.13 on 2025-10-20 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=payments.models._gen_public_id, editable=False, max_length=16, unique=True)),
                ('gateway', models.CharField(choices=[('sadad', 'سداد (بانک ملّی)'), ('fake', 'درگاه آزمایشی')], default='fake', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'ایجاد شده'), ('redirected', 'ارسال به درگاه'), ('paid', 'پرداخت موفق'), ('failed', 'ناموفق/لغو')], default='initiated', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('callback_url', models.URLField(blank=True, default='')),
                ('token', models.CharField(blank=True, default='', max_length=128)),
                ('ref_id', models.CharField(blank=True, default='', max_length=64)),
                ('card_pan', models.CharField(blank=True, default='', max_length=64)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('initiator_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='competitions.kyorugicompetition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش/Intent',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_f8bf5e_idx'), models.Index(fields=['token'], name='payments_pa_token_8c4599_idx'), models.Index(fields=['created_at'], name='payments_pa_created_8a067b_idx')],
            },
        ),
    ]
