# Generated by Django 3.2.25 on 2025-11-01 12:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='kyorugi_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='competitions.enrollment'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='poomsae_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='competitions.poomsaeenrollment'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='seminar_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='competitions.seminarregistration'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway',
            field=models.CharField(choices=[('sadad', 'سداد (بانک ملّی)'), ('fake', 'درگاه آزمایشی')], default='sadad', max_length=20),
        ),
    ]
