# Generated by Django 4.2.13 on 2025-11-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20251101_1539'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kyorugi_enrollment__isnull', True), ('poomsae_enrollment__isnull', True)), models.Q(('kyorugi_enrollment__isnull', True), ('seminar_registration__isnull', True)), models.Q(('poomsae_enrollment__isnull', True), ('seminar_registration__isnull', True)), _connector='OR'), name='payments_at_most_one_target_fk'),
        ),
    ]
