# Generated by Django 4.2.13 on 2025-11-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentintent_payments_at_most_one_target_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway',
            field=models.CharField(choices=[('sadad', 'سداد (بانک ملّی)'), ('fake', 'درگاه آزمایشی'), ('dummy', 'درگاه نمایشی (تست)')], default='sadad', max_length=20),
        ),
    ]
