# Generated by Django 4.2.13 on 2025-11-30 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_discountcode'),
        ('payments', '0004_alter_paymentintent_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='competitions.discountcode'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='original_amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
