# Generated by Django 4.2.13 on 2026-01-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentintent_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='payment_link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment_link_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
