# Generated by Django 4.2.13 on 2026-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_enrollment_enrollments_created'),
        ('payments', '0006_paymentintent_payment_link_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='kyorugi_enrollments',
            field=models.ManyToManyField(blank=True, related_name='bulk_payment_intents', to='competitions.enrollment'),
        ),
    ]
