# Generated by Django 4.2.13 on 2026-01-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentintent_kyorugi_enrollments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentintent',
            name='payments_at_most_one_target_fk',
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway',
            field=models.CharField(choices=[('sadad', 'سداد (بانک ملّی)'), ('bmi', 'سداد/BMI (azbankgateways)'), ('fake', 'درگاه آزمایشی'), ('dummy', 'درگاه نمایشی (تست)')], default='sadad', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kyorugi_enrollment__isnull', True), ('poomsae_enrollment__isnull', True), ('seminar_registration__isnull', True)), models.Q(('kyorugi_enrollment__isnull', False), ('poomsae_enrollment__isnull', True), ('seminar_registration__isnull', True)), models.Q(('kyorugi_enrollment__isnull', True), ('poomsae_enrollment__isnull', False), ('seminar_registration__isnull', True)), models.Q(('kyorugi_enrollment__isnull', True), ('poomsae_enrollment__isnull', True), ('seminar_registration__isnull', False)), _connector='OR'), name='payments_at_most_one_target_fk'),
        ),
    ]
