# Generated by Django 4.2.13 on 2025-10-25 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_phone_lengths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachclubrequest',
            options={'verbose_name': 'درخواست ارتباط مربی-باشگاه', 'verbose_name_plural': 'درخواست\u200cهای ارتباط مربی-باشگاه'},
        ),
        migrations.AlterModelOptions(
            name='smsverification',
            options={'verbose_name': 'کد تأیید پیامکی', 'verbose_name_plural': 'کدهای تأیید پیامکی'},
        ),
        migrations.AlterField(
            model_name='coachclubrequest',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tkdclub', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='coachclubrequest',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_requests', to='accounts.userprofile', verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='coachclubrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='coachclubrequest',
            name='request_type',
            field=models.CharField(choices=[('add', 'افزودن'), ('remove', 'حذف')], max_length=10, verbose_name='نوع درخواست'),
        ),
        migrations.AlterField(
            model_name='coachclubrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='activity_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات فعالیت'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='club_type',
            field=models.CharField(choices=[('private', 'خصوصی'), ('governmental', 'دولتی'), ('other', 'سایر')], max_length=20, verbose_name='نوع باشگاه'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='confirm_info',
            field=models.BooleanField(default=False, verbose_name='اطلاعات تأیید شده'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='county',
            field=models.CharField(max_length=100, verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='federation_id',
            field=models.CharField(max_length=100, verbose_name='شناسه فدراسیون'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='founder_name',
            field=models.CharField(max_length=100, verbose_name='نام مؤسس'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='founder_national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی مؤسس'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='founder_phone',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل مؤسس'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='license_image',
            field=models.ImageField(upload_to='club_licenses/', verbose_name='تصویر مجوز'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='license_number',
            field=models.CharField(max_length=100, verbose_name='شماره مجوز'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تلفن باشگاه'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='province',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='tkd_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_clubs', to='accounts.tkdboard', verbose_name='هیئت'),
        ),
        migrations.AlterField(
            model_name='pendingclub',
            name='tkd_board_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام هیئت (متنی)'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='belt_certificate_date',
            field=models.CharField(help_text='فرمت: ۱۴۰۳/۰۴/۱۰', max_length=10, verbose_name='تاریخ گواهی کمربند'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='belt_certificate_number',
            field=models.CharField(max_length=50, verbose_name='شماره گواهی کمربند'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='belt_grade',
            field=models.CharField(choices=[('سفید', 'سفید'), ('زرد', 'زرد'), ('سبز', 'سبز'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('مشکی دان 1', 'مشکی دان 1'), ('مشکی دان 2', 'مشکی دان 2'), ('مشکی دان 3', 'مشکی دان 3'), ('مشکی دان 4', 'مشکی دان 4'), ('مشکی دان 5', 'مشکی دان 5'), ('مشکی دان 6', 'مشکی دان 6'), ('مشکی دان 7', 'مشکی دان 7'), ('مشکی دان 8', 'مشکی دان 8'), ('مشکی دان 9', 'مشکی دان 9'), ('مشکی دان 10', 'مشکی دان 10')], max_length=20, verbose_name='درجه کمربند'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='birth_date',
            field=models.CharField(help_text='فرمت: ۱۴۰۳/۰۴/۱۰', max_length=10, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_edit_members', to='accounts.tkdclub', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='club_names',
            field=models.JSONField(blank=True, default=list, verbose_name='نام باشگاه\u200cها (متنی)'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_edit_students', to='accounts.userprofile', verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='coach_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه مربیگری'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='coach_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه مربیگری بین\u200cالمللی'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='coach_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام مربی (متنی)'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='coaching_clubs',
            field=models.ManyToManyField(blank=True, related_name='pending_edit_coaches', to='accounts.tkdclub', verbose_name='باشگاه\u200cهای تحت مربیگری'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='confirm_info',
            field=models.BooleanField(default=False, verbose_name='اطلاعات تأیید شده'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='county',
            field=models.CharField(max_length=50, verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='father_name',
            field=models.CharField(max_length=50, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='hanmadang',
            field=models.BooleanField(default=False, verbose_name='هان مادانگ'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='hanmadang_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه هان مادانگ'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='hanmadang_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه بین\u200cالمللی هان مادانگ'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='is_coach',
            field=models.BooleanField(default=False, verbose_name='مربی است؟'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='is_referee',
            field=models.BooleanField(default=False, verbose_name='داور است؟'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='kyorogi',
            field=models.BooleanField(default=False, verbose_name='کیوروگی'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='kyorogi_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه کیوروگی'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='kyorogi_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه بین\u200cالمللی کیوروگی'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='original_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_request', to='accounts.userprofile', verbose_name='کاربر اصلی'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='poomseh',
            field=models.BooleanField(default=False, verbose_name='پومسه'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='poomseh_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه پومسه'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='poomseh_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه بین\u200cالمللی پومسه'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='profile_image',
            field=models.ImageField(upload_to='pending_photos/', verbose_name='عکس پروفایل (در انتظار تأیید)'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='province',
            field=models.CharField(max_length=50, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='role',
            field=models.CharField(choices=[('player', 'بازیکن'), ('coach', 'مربی'), ('referee', 'داور'), ('both', 'مربی و داور')], default='player', max_length=10, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='tkd_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tkdboard', verbose_name='هیئت'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='tkd_board_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام هیئت (متنی)'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='belt_certificate_date',
            field=models.CharField(help_text='فرمت: ۱۴۰۳/۰۴/۱۰', max_length=10, verbose_name='تاریخ گواهی کمربند'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='belt_certificate_number',
            field=models.CharField(max_length=50, verbose_name='شماره گواهی کمربند'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='belt_grade',
            field=models.CharField(choices=[('سفید', 'سفید'), ('زرد', 'زرد'), ('سبز', 'سبز'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('مشکی دان 1', 'مشکی دان 1'), ('مشکی دان 2', 'مشکی دان 2'), ('مشکی دان 3', 'مشکی دان 3'), ('مشکی دان 4', 'مشکی دان 4'), ('مشکی دان 5', 'مشکی دان 5'), ('مشکی دان 6', 'مشکی دان 6'), ('مشکی دان 7', 'مشکی دان 7'), ('مشکی دان 8', 'مشکی دان 8'), ('مشکی دان 9', 'مشکی دان 9'), ('مشکی دان 10', 'مشکی دان 10')], max_length=20, verbose_name='درجه کمربند'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='birth_date',
            field=models.CharField(help_text='فرمت: ۱۴۰۳/۰۴/۱۰', max_length=10, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_members', to='accounts.tkdclub', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='club_names',
            field=models.JSONField(blank=True, default=list, verbose_name='نام باشگاه\u200cها (متنی)'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_students', to='accounts.userprofile', verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='coach_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه مربیگری'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='coach_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه مربیگری بین\u200cالمللی'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='coach_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام مربی (متنی)'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='coaching_clubs',
            field=models.ManyToManyField(blank=True, related_name='pending_coaches', to='accounts.tkdclub', verbose_name='باشگاه\u200cهای تحت مربیگری'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='confirm_info',
            field=models.BooleanField(default=False, verbose_name='اطلاعات تأیید شده'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='county',
            field=models.CharField(max_length=50, verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='father_name',
            field=models.CharField(max_length=50, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='hanmadang',
            field=models.BooleanField(default=False, verbose_name='هان مادانگ'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='hanmadang_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه هان مادانگ'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='hanmadang_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه بین\u200cالمللی هان مادانگ'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='is_coach',
            field=models.BooleanField(default=False, verbose_name='مربی است؟'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='is_referee',
            field=models.BooleanField(default=False, verbose_name='داور است؟'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='kyorogi',
            field=models.BooleanField(default=False, verbose_name='کیوروگی'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='kyorogi_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه کیوروگی'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='kyorogi_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه بین\u200cالمللی کیوروگی'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='poomseh',
            field=models.BooleanField(default=False, verbose_name='پومسه'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='poomseh_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه پومسه'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='poomseh_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه بین\u200cالمللی پومسه'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='profile_image',
            field=models.ImageField(upload_to='pending_photos/', verbose_name='عکس پروفایل (در انتظار تأیید)'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='province',
            field=models.CharField(max_length=50, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='role',
            field=models.CharField(choices=[('player', 'بازیکن'), ('coach', 'مربی'), ('referee', 'داور'), ('both', 'مربی و داور')], default='player', max_length=10, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='tkd_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tkdboard', verbose_name='هیئت'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='tkd_board_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام هیئت (متنی)'),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='code',
            field=models.CharField(max_length=4, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='tkdboard',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='tkdboard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام هیئت'),
        ),
        migrations.AlterField(
            model_name='tkdboard',
            name='province',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='tkdboard',
            name='ranking_total',
            field=models.FloatField(default=0, verbose_name='امتیاز کل'),
        ),
        migrations.AlterField(
            model_name='tkdboard',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='activity_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات فعالیت'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='bronze_medals',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال\u200cهای برنز'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='club_type',
            field=models.CharField(choices=[('private', 'خصوصی'), ('governmental', 'دولتی'), ('other', 'سایر')], max_length=20, verbose_name='نوع باشگاه'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='coach_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد مربیان'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='confirm_info',
            field=models.BooleanField(default=False, verbose_name='اطلاعات تأیید شده'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='county',
            field=models.CharField(max_length=100, verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='federation_id',
            field=models.CharField(max_length=100, verbose_name='شناسه فدراسیون'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='founder_name',
            field=models.CharField(max_length=100, verbose_name='نام مؤسس'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='founder_national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی مؤسس'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='founder_phone',
            field=models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل مؤسس'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='gold_medals',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال\u200cهای طلا'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='license_image',
            field=models.ImageField(upload_to='club_licenses/', verbose_name='تصویر مجوز'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='license_number',
            field=models.CharField(max_length=100, verbose_name='شماره مجوز'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='matches_participated',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد حضور در مسابقات'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تلفن باشگاه'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='province',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='ranking_competition',
            field=models.FloatField(default=0, verbose_name='امتیاز مسابقات'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='ranking_total',
            field=models.FloatField(default=0, verbose_name='امتیاز کل'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='silver_medals',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال\u200cهای نقره'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد ورزشکاران'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='tkd_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='accounts.tkdboard', verbose_name='هیئت'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='belt_certificate_date',
            field=models.CharField(help_text='فرمت: ۱۴۰۳/۰۴/۱۰', max_length=10, verbose_name='تاریخ گواهی کمربند'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='belt_certificate_number',
            field=models.CharField(max_length=50, verbose_name='شماره گواهی کمربند'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='belt_grade',
            field=models.CharField(choices=[('سفید', 'سفید'), ('زرد', 'زرد'), ('سبز', 'سبز'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('مشکی دان 1', 'مشکی دان 1'), ('مشکی دان 2', 'مشکی دان 2'), ('مشکی دان 3', 'مشکی دان 3'), ('مشکی دان 4', 'مشکی دان 4'), ('مشکی دان 5', 'مشکی دان 5'), ('مشکی دان 6', 'مشکی دان 6'), ('مشکی دان 7', 'مشکی دان 7'), ('مشکی دان 8', 'مشکی دان 8'), ('مشکی دان 9', 'مشکی دان 9'), ('مشکی دان 10', 'مشکی دان 10')], max_length=20, verbose_name='درجه کمربند'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.CharField(help_text='فرمت: ۱۴۰۳/۰۴/۱۰', max_length=10, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bronze_medals',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال برنز'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bronze_medals_country',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال برنز (کشوری)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bronze_medals_int',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال برنز (بین\u200cالمللی)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.tkdclub', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='club_names',
            field=models.JSONField(blank=True, default=list, verbose_name='نام باشگاه\u200cها (متنی)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.userprofile', verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coach_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه مربیگری'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coach_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه مربیگری بین\u200cالمللی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coach_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام مربی (متنی)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coaching_clubs',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='accounts.tkdclub', verbose_name='باشگاه\u200cهای تحت مربیگری'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='confirm_info',
            field=models.BooleanField(default=False, verbose_name='اطلاعات تأیید شده'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(max_length=50, verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(max_length=50, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gold_medals',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال طلا'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gold_medals_country',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال طلا (کشوری)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gold_medals_int',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال طلا (بین\u200cالمللی)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hanmadang',
            field=models.BooleanField(default=False, verbose_name='هان مادانگ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hanmadang_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه هان مادانگ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hanmadang_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه بین\u200cالمللی هان مادانگ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_coach',
            field=models.BooleanField(default=False, verbose_name='مربی است؟'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_referee',
            field=models.BooleanField(default=False, verbose_name='داور است؟'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kyorogi',
            field=models.BooleanField(default=False, verbose_name='کیوروگی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kyorogi_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه کیوروگی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kyorogi_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه بین\u200cالمللی کیوروگی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='match_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد مسابقات'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='poomseh',
            field=models.BooleanField(default=False, verbose_name='پومسه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='poomseh_level',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه پومسه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='poomseh_level_International',
            field=models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='درجه بین\u200cالمللی پومسه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(upload_to='player_photos/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.CharField(max_length=50, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ranking_competition',
            field=models.FloatField(default=0, verbose_name='امتیاز مسابقات'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ranking_total',
            field=models.FloatField(default=0, verbose_name='امتیاز کل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('player', 'بازیکن'), ('coach', 'مربی'), ('referee', 'داور'), ('both', 'مربی و داور')], default='player', max_length=10, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='seminar_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد سمینارها'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='silver_medals',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال نقره'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='silver_medals_country',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال نقره (کشوری)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='silver_medals_int',
            field=models.PositiveIntegerField(default=0, verbose_name='مدال نقره (بین\u200cالمللی)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tkd_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tkdboard', verbose_name='هیئت'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tkd_board_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام هیئت (متنی)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط'),
        ),
    ]
