# Generated by Django 4.2.13 on 2025-11-16 13:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_coachclubrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingclub',
            name='license_image',
            field=models.ImageField(upload_to=accounts.models.club_license_upload, verbose_name='تصویر مجوز'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='pending_photos/', verbose_name='عکس پروفایل (در انتظار تأیید)'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='profile_image',
            field=models.ImageField(upload_to='pending_photos/', verbose_name='عکس پرسنلی (در انتظار تأیید)'),
        ),
        migrations.AlterField(
            model_name='tkdclub',
            name='license_image',
            field=models.ImageField(upload_to=accounts.models.club_license_upload, verbose_name='تصویر مجوز'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(upload_to='player_photos/', verbose_name='عکس پرسنلی'),
        ),
    ]
