# Generated by Django 4.2.13 on 2025-12-12 16:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_pendingclub_license_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.pending_photo_upload, verbose_name='عکس پروفایل (در انتظار تأیید)'),
        ),
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='profile_image',
            field=models.ImageField(upload_to=accounts.models.pending_photo_upload, verbose_name='عکس پرسنلی (در انتظار تأیید)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(upload_to=accounts.models.player_photo_upload, verbose_name='عکس پرسنلی'),
        ),
    ]
