# Generated by Django 4.2.13 on 2026-02-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pendingeditprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='نام فیلد تغییر یافته')),
                ('old_value', models.TextField(verbose_name='مقدار قدیمی')),
                ('new_value', models.TextField(verbose_name='مقدار جدید')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'تاریخچه تغییرات پروفایل',
                'verbose_name_plural': 'تاریخچه تغییرات پروفایل\u200cها',
            },
        ),
    ]
