# Generated by Django 4.2.13 on 2025-10-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCenter',
            fields=[
            ],
            options={
                'verbose_name': 'مرکز گزارش\u200cگیری',
                'verbose_name_plural': 'مرکز گزارش\u200cگیری',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.userprofile',),
        ),
    ]
