# Generated by Django 4.2.13 on 2025-11-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='target_type',
            field=models.CharField(blank=True, choices=[('competition', 'competition'), ('seminar', 'seminar')], db_index=True, max_length=20, null=True),
        ),
    ]
