# Generated by Django 4.2.13 on 2025-10-20 15:47

import competitions.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان رده سنی')),
                ('from_date', models.DateField(verbose_name='از تاریخ تولد')),
                ('to_date', models.DateField(verbose_name='تا تاریخ تولد')),
            ],
            options={
                'verbose_name': 'رده سنی',
                'verbose_name_plural': 'رده\u200cهای سنی',
            },
        ),
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کمربند')),
            ],
            options={
                'verbose_name': 'کمربند',
                'verbose_name_plural': 'کمربندها',
            },
        ),
        migrations.CreateModel(
            name='BeltGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='نام گروه کمربند')),
            ],
            options={
                'verbose_name': 'گروه کمربند',
                'verbose_name_plural': 'گروه\u200cهای کمربند',
            },
        ),
        migrations.CreateModel(
            name='CoachApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='کد تأیید مربی')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='تعهدنامه پذیرفته شد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تأیید')),
            ],
            options={
                'verbose_name': 'تأیید مربی برای مسابقه',
                'verbose_name_plural': 'تأییدهای مربیان',
            },
        ),
        migrations.CreateModel(
            name='CompetitionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kyorugi_files/', verbose_name='فایل PDF')),
            ],
            options={
                'verbose_name': 'فایل مسابقه',
                'verbose_name_plural': 'فایل\u200cهای مسابقه',
            },
        ),
        migrations.CreateModel(
            name='CompetitionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kyorugi_images/', verbose_name='تصویر پیوست')),
            ],
            options={
                'verbose_name': 'تصویر مسابقه',
                'verbose_name_plural': 'تصاویر مسابقه',
            },
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, verbose_name='جنسیت')),
                ('size', models.PositiveIntegerField(help_text='مثل 8، 16، 32', verbose_name='اندازه جدول (توان ۲)')),
                ('club_threshold', models.PositiveIntegerField(default=8, verbose_name='آستانه هم\u200cباشگاهی')),
                ('rng_seed', models.CharField(blank=True, default='', max_length=32, verbose_name='Seed تصادفی')),
                ('is_locked', models.BooleanField(default=False, verbose_name='قفل شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
            ],
            options={
                'verbose_name': 'قرعه',
                'verbose_name_plural': 'قرعه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(blank=True, default='', max_length=150)),
                ('coach_approval_code', models.CharField(blank=True, default='', max_length=8)),
                ('club_name', models.CharField(blank=True, default='', max_length=150)),
                ('board_name', models.CharField(blank=True, default='', max_length=150)),
                ('declared_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('insurance_number', models.CharField(max_length=20)),
                ('insurance_issue_date', models.DateField()),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('confirmed', 'تأیید نهایی'), ('accepted', 'پذیرفته\u200cشده'), ('completed', 'تکمیل\u200cشده'), ('canceled', 'لغو شده')], default='pending_payment', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('bank_ref_code', models.CharField(blank=True, default='', max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('medal', models.CharField(blank=True, choices=[('', '—'), ('gold', 'طلا'), ('silver', 'نقره'), ('bronze', 'برنز')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstRoundPairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('last_met_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KyorugiCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_manual', models.BooleanField(blank=True, default=None, help_text='خالی=طبق تاریخ\u200cها، تیک=اجباراً باز، بدون تیک=اجباراً بسته', null=True, verbose_name='فعال بودن ثبت\u200cنام')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مسابقه')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='kyorugi_posters/', verbose_name='پوستر شاخص')),
                ('entry_fee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ ورودی (تومان)')),
                ('belt_level', models.CharField(choices=[('yellow_blue', 'زرد تا آبی'), ('red_black', 'قرمز و مشکی'), ('all', 'همه رده\u200cها')], max_length=20, verbose_name='رده کمربندی')),
                ('gender', models.CharField(choices=[('male', 'آقایان'), ('female', 'بانوان')], max_length=10, verbose_name='جنسیت')),
                ('city', models.CharField(max_length=100, verbose_name='شهر محل برگزاری')),
                ('address', models.TextField(verbose_name='آدرس محل برگزاری')),
                ('registration_start', models.DateField(verbose_name='شروع ثبت\u200cنام')),
                ('registration_end', models.DateField(verbose_name='پایان ثبت\u200cنام')),
                ('weigh_date', models.DateField(verbose_name='تاریخ وزن\u200cکشی')),
                ('draw_date', models.DateField(verbose_name='تاریخ قرعه\u200cکشی')),
                ('competition_date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('bracket_published_at', models.DateTimeField(blank=True, null=True)),
                ('mat_count', models.PositiveIntegerField(default=1, verbose_name='تعداد زمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('public_id', models.CharField(db_index=True, default=competitions.models._gen_public_id, editable=False, max_length=16, unique=True, verbose_name='شناسه عمومی')),
            ],
            options={
                'verbose_name': 'مسابقه کیوروگی',
                'verbose_name_plural': 'مسابقات کیوروگی',
            },
        ),
        migrations.CreateModel(
            name='KyorugiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نتیجه وزن',
                'verbose_name_plural': 'نتایج اوزان',
            },
        ),
        migrations.CreateModel(
            name='MatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_number', models.PositiveIntegerField(verbose_name='شماره زمین')),
            ],
            options={
                'verbose_name': 'تخصیص زمین',
                'verbose_name_plural': 'تخصیص اوزان به زمین\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(help_text='1 = دور اول', verbose_name='دور')),
                ('slot_a', models.PositiveIntegerField(verbose_name='اسلات A')),
                ('slot_b', models.PositiveIntegerField(verbose_name='اسلات B')),
                ('is_bye', models.BooleanField(default=False, verbose_name='BYE؟')),
                ('mat_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمین')),
                ('match_number', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='شماره بازی')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان\u200cبندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
            ],
            options={
                'verbose_name': 'مبارزه',
                'verbose_name_plural': 'مبارزات',
            },
        ),
        migrations.CreateModel(
            name='PoomsaeCoachApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='کد تأیید مربی')),
                ('approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تأیید مربی پومسه',
                'verbose_name_plural': 'تأییدهای مربی پومسه',
            },
        ),
        migrations.CreateModel(
            name='PoomsaeCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_manual', models.BooleanField(blank=True, default=None, help_text='خالی=طبق تاریخ\u200cها، تیک=اجباراً باز، بدون تیک=اجباراً بسته', null=True, verbose_name='فعال بودن ثبت\u200cنام')),
                ('public_id', models.SlugField(default=competitions.models._gen_public_id, editable=False, max_length=16, unique=True, verbose_name='شناسه عمومی')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان مسابقه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='poomsae_posters/', verbose_name='پوستر شاخص')),
                ('belt_level', models.CharField(blank=True, choices=[('yellow_blue', 'زرد تا آبی'), ('red_black', 'قرمز و مشکی'), ('all', 'همه رده\u200cها')], default='all', max_length=20, verbose_name='رده کمربندی')),
                ('gender', models.CharField(blank=True, choices=[('male', 'آقایان'), ('female', 'بانوان')], default='', max_length=10, verbose_name='جنسیت')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='شهر محل برگزاری')),
                ('address', models.TextField(blank=True, default='', verbose_name='آدرس محل برگزاری')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع مسابقه')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان مسابقه')),
                ('registration_start', models.DateTimeField(verbose_name='شروع ثبت\u200cنام')),
                ('registration_end', models.DateTimeField(verbose_name='پایان ثبت\u200cنام')),
                ('draw_date', models.DateField(blank=True, null=True, verbose_name='تاریخ قرعه\u200cکشی')),
                ('competition_date', models.DateField(blank=True, null=True, verbose_name='تاریخ برگزاری')),
                ('entry_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه ورودی (تومان)')),
                ('terms_text', models.TextField(blank=True, verbose_name='متن قوانین و مقررات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مسابقه پومسه',
                'verbose_name_plural': 'مسابقات پومسه',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoomsaeDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('standard', 'استاندارد'), ('creative', 'ابداعی')], max_length=20, verbose_name='سبک مسابقه')),
            ],
            options={
                'verbose_name': 'رده پومسه',
                'verbose_name_plural': 'رده\u200cهای پومسه',
            },
        ),
        migrations.CreateModel(
            name='PoomsaeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(blank=True, default='', max_length=150, verbose_name='نام مربی (اسنپ\u200cشات)')),
                ('coach_approval_code', models.CharField(blank=True, default='', max_length=8, verbose_name='کد تایید مربی (اسنپ\u200cشات)')),
                ('club_name', models.CharField(blank=True, default='', max_length=150, verbose_name='نام باشگاه (اسنپ\u200cشات)')),
                ('board_name', models.CharField(blank=True, default='', max_length=150, verbose_name='نام هیئت (اسنپ\u200cشات)')),
                ('poomsae_type', models.CharField(choices=[('standard', 'استاندارد'), ('creative', 'ابداعی')], max_length=16, verbose_name='نوع پومسه')),
                ('insurance_number', models.CharField(max_length=20, verbose_name='شماره بیمه')),
                ('insurance_issue_date', models.DateField(verbose_name='تاریخ صدور بیمه')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('confirmed', 'تأیید نهایی'), ('accepted', 'پذیرفته\u200cشده'), ('completed', 'تکمیل\u200cشده'), ('canceled', 'لغو شده')], default='pending_payment', max_length=20, verbose_name='وضعیت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('paid_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداختی (تومان)')),
                ('bank_ref_code', models.CharField(blank=True, default='', max_length=64, verbose_name='کد مرجع بانکی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('medal', models.CharField(blank=True, choices=[('', '—'), ('gold', 'طلا'), ('silver', 'نقره'), ('bronze', 'برنز')], default='', max_length=10, verbose_name='مدال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام پومسه',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای پومسه',
            },
        ),
        migrations.CreateModel(
            name='PoomsaeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='poomsae_files/', verbose_name='فایل PDF')),
            ],
            options={
                'verbose_name': 'فایل مسابقه پومسه',
                'verbose_name_plural': 'فایل\u200cهای مسابقه پومسه',
            },
        ),
        migrations.CreateModel(
            name='PoomsaeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='poomsae_images/', verbose_name='تصویر پیوست')),
            ],
            options={
                'verbose_name': 'تصویر مسابقه پومسه',
                'verbose_name_plural': 'تصاویر مسابقه پومسه',
            },
        ),
        migrations.CreateModel(
            name='RankingAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=255)),
                ('coach_name', models.CharField(blank=True, max_length=255)),
                ('club_name', models.CharField(blank=True, max_length=255)),
                ('board_name', models.CharField(blank=True, max_length=255)),
                ('points_player', models.FloatField(default=0.0)),
                ('points_coach', models.FloatField(default=0.0)),
                ('points_club', models.FloatField(default=0.0)),
                ('points_board', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('player', 'بازیکن'), ('coach', 'مربی'), ('club', 'باشگاه'), ('board', 'هیئت')], max_length=16)),
                ('subject_id', models.IntegerField()),
                ('medal', models.CharField(blank=True, default='', max_length=10)),
                ('points', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='seminars/posters/', verbose_name='پوستر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('registration_start', models.DateField(verbose_name='شروع ثبت\u200cنام')),
                ('registration_end', models.DateField(verbose_name='پایان ثبت\u200cنام')),
                ('event_date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('fee', models.PositiveIntegerField(default=0, verbose_name='هزینه (تومان)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='مکان برگزاری')),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text="مثلاً ['player','coach'] — خالی = همه نقش\u200cها", verbose_name='نقش\u200cهای مجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('public_id', models.CharField(db_index=True, default=competitions.models._seminar_default_public_id, editable=False, max_length=16, unique=True, verbose_name='شناسه عمومی')),
            ],
            options={
                'verbose_name': 'سمینار',
                'verbose_name_plural': 'سمینارها',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تعهدنامه')),
                ('content', models.TextField(verbose_name='متن تعهدنامه')),
            ],
            options={
                'verbose_name': 'قالب تعهدنامه',
                'verbose_name_plural': 'قالب\u200cهای تعهدنامه',
            },
        ),
        migrations.CreateModel(
            name='WeightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام وزن')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=6, verbose_name='جنسیت')),
                ('min_weight', models.FloatField(verbose_name='حداقل وزن (kg)')),
                ('max_weight', models.FloatField(verbose_name='حداکثر وزن (kg)')),
                ('tolerance', models.FloatField(default=0.2, verbose_name='میزان ارفاق وزنی (kg)')),
            ],
            options={
                'verbose_name': 'رده وزنی',
                'verbose_name_plural': 'رده\u200cهای وزنی',
            },
        ),
        migrations.CreateModel(
            name='SeminarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(blank=True, default=list, help_text="مثال: ['coach']", verbose_name='نقش/نقش\u200cها')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='تلفن تماس')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('paid_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداختی (تومان)')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.seminar', verbose_name='سمینار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_registrations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام سمینار',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای سمینار',
            },
        ),
        migrations.AddIndex(
            model_name='seminar',
            index=models.Index(fields=['public_id'], name='competition_public__3683fa_idx'),
        ),
        migrations.AddIndex(
            model_name='seminar',
            index=models.Index(fields=['event_date'], name='competition_event_d_ff54ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='seminar',
            constraint=models.CheckConstraint(check=models.Q(('registration_start__lte', models.F('registration_end'))), name='seminar_reg_start_lte_reg_end'),
        ),
        migrations.AddConstraint(
            model_name='seminar',
            constraint=models.CheckConstraint(check=models.Q(('registration_end__lte', models.F('event_date'))), name='seminar_reg_end_lte_event_date'),
        ),
        migrations.AddField(
            model_name='rankingtransaction',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_transactions', to='competitions.kyorugicompetition'),
        ),
        migrations.AddField(
            model_name='rankingtransaction',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='competitions.kyorugiresult'),
        ),
        migrations.AddField(
            model_name='rankingaward',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_as_board', to='accounts.tkdboard'),
        ),
        migrations.AddField(
            model_name='rankingaward',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_as_club', to='accounts.tkdclub'),
        ),
        migrations.AddField(
            model_name='rankingaward',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_as_coach', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='rankingaward',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_award', to='competitions.enrollment'),
        ),
        migrations.AddField(
            model_name='rankingaward',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_as_player', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='poomsaeimage',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='competitions.poomsaecompetition', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='poomsaefile',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='competitions.poomsaecompetition', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poomsae_enrollments', to='competitions.agecategory', verbose_name='رده سنی'),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='belt_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_enrollments', to='competitions.beltgroup', verbose_name='گروه کمربندی'),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_board_enrollments', to='accounts.tkdboard', verbose_name='هیئت'),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_club_enrollments', to='accounts.tkdclub', verbose_name='باشگاه'),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_coach_enrollments', to='accounts.userprofile', verbose_name='مربی'),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='competitions.poomsaecompetition', verbose_name='مسابقه پومسه'),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poomsae_enrollments', to='accounts.userprofile', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='poomsaedivision',
            name='age_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.agecategory', verbose_name='گروه سنی'),
        ),
        migrations.AddField(
            model_name='poomsaedivision',
            name='belt_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.beltgroup', verbose_name='رده کمربندی'),
        ),
        migrations.AddField(
            model_name='poomsaedivision',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='competitions.poomsaecompetition', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='age_categories',
            field=models.ManyToManyField(blank=True, related_name='poom_competitions', to='competitions.agecategory'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.agecategory', verbose_name='گروه سنی'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='belt_groups',
            field=models.ManyToManyField(blank=True, to='competitions.beltgroup', verbose_name='گروه\u200cهای کمربندی'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='terms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_competitions', to='competitions.termstemplate', verbose_name='قالب تعهدنامه'),
        ),
        migrations.AddField(
            model_name='poomsaecoachapproval',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='poomsae_coach_approvals', to='accounts.userprofile', verbose_name='مربی'),
        ),
        migrations.AddField(
            model_name='poomsaecoachapproval',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_approvals', to='competitions.poomsaecompetition', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='poomsaecoachapproval',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poomsae_approvals', to='accounts.userprofile', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='match',
            name='draw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.draw', verbose_name='قرعه'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_player_a', to='accounts.userprofile', verbose_name='بازیکن A'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_player_b', to='accounts.userprofile', verbose_name='بازیکن B'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_winner', to='accounts.userprofile', verbose_name='برنده'),
        ),
        migrations.AddField(
            model_name='matassignment',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_assignments', to='competitions.kyorugicompetition', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='matassignment',
            name='weights',
            field=models.ManyToManyField(to='competitions.weightcategory', verbose_name='اوزان تخصیص\u200cیافته'),
        ),
        migrations.AddField(
            model_name='kyorugiresult',
            name='bronze1_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.enrollment'),
        ),
        migrations.AddField(
            model_name='kyorugiresult',
            name='bronze2_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.enrollment'),
        ),
        migrations.AddField(
            model_name='kyorugiresult',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.kyorugicompetition'),
        ),
        migrations.AddField(
            model_name='kyorugiresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kyorugiresult',
            name='gold_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.enrollment'),
        ),
        migrations.AddField(
            model_name='kyorugiresult',
            name='silver_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.enrollment'),
        ),
        migrations.AddField(
            model_name='kyorugiresult',
            name='weight_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.weightcategory'),
        ),
        migrations.AddField(
            model_name='kyorugicompetition',
            name='age_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.agecategory', verbose_name='رده سنی'),
        ),
        migrations.AddField(
            model_name='kyorugicompetition',
            name='belt_groups',
            field=models.ManyToManyField(blank=True, to='competitions.beltgroup', verbose_name='گروه\u200cهای کمربندی'),
        ),
        migrations.AddField(
            model_name='kyorugicompetition',
            name='bracket_published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_kyorugi_brackets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kyorugicompetition',
            name='terms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='competitions.termstemplate', verbose_name='قالب تعهدنامه'),
        ),
        migrations.AddField(
            model_name='firstroundpairhistory',
            name='age_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.agecategory'),
        ),
        migrations.AddField(
            model_name='firstroundpairhistory',
            name='belt_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.beltgroup'),
        ),
        migrations.AddField(
            model_name='firstroundpairhistory',
            name='last_competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.kyorugicompetition'),
        ),
        migrations.AddField(
            model_name='firstroundpairhistory',
            name='player_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='firstroundpairhistory',
            name='player_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='firstroundpairhistory',
            name='weight_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.weightcategory'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='belt_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='competitions.beltgroup'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_enrollments', to='accounts.tkdboard'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_enrollments', to='accounts.tkdclub'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_enrollments', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='competitions.kyorugicompetition'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='weight_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='competitions.weightcategory'),
        ),
        migrations.AddField(
            model_name='draw',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='competitions.agecategory'),
        ),
        migrations.AddField(
            model_name='draw',
            name='belt_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.beltgroup', verbose_name='گروه کمربندی'),
        ),
        migrations.AddField(
            model_name='draw',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='competitions.kyorugicompetition', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='draw',
            name='weight_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.weightcategory', verbose_name='رده وزنی'),
        ),
        migrations.AddField(
            model_name='competitionimage',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='competitions.kyorugicompetition', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='competitionfile',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='competitions.kyorugicompetition', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='coachapproval',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='competition_approvals', to='accounts.userprofile', verbose_name='مربی'),
        ),
        migrations.AddField(
            model_name='coachapproval',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_approvals', to='competitions.kyorugicompetition', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='beltgroup',
            name='belts',
            field=models.ManyToManyField(to='competitions.belt', verbose_name='کمربندها'),
        ),
        migrations.CreateModel(
            name='CoachApprovalsEntry',
            fields=[
            ],
            options={
                'verbose_name': 'تأیید مربیان',
                'verbose_name_plural': 'تأیید مربیان',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.kyorugicompetition',),
        ),
        migrations.CreateModel(
            name='DrawStart',
            fields=[
            ],
            options={
                'verbose_name': 'شروع قرعه\u200cکشی',
                'verbose_name_plural': 'شروع قرعه\u200cکشی',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.draw',),
        ),
        migrations.CreateModel(
            name='KyorugiCompetitionParticipantsReport',
            fields=[
            ],
            options={
                'verbose_name': 'لیست شرکت\u200cکنندگان مسابقات',
                'verbose_name_plural': 'لیست شرکت\u200cکنندگان مسابقات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.kyorugicompetition',),
        ),
        migrations.CreateModel(
            name='NumberingEntry',
            fields=[
            ],
            options={
                'verbose_name': 'شماره\u200cگذاری بازی\u200cها',
                'verbose_name_plural': 'شماره\u200cگذاری بازی\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.kyorugicompetition',),
        ),
        migrations.CreateModel(
            name='SeminarAttendee',
            fields=[
            ],
            options={
                'verbose_name': 'لیست شرکت\u200cکنندگان سمینارها',
                'verbose_name_plural': 'لیست شرکت\u200cکنندگان سمینارها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.seminarregistration',),
        ),
        migrations.CreateModel(
            name='SeminarParticipants',
            fields=[
            ],
            options={
                'verbose_name': 'لیست شرکت\u200cکنندگان سمینارها',
                'verbose_name_plural': 'لیست شرکت\u200cکنندگان سمینارها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.seminarregistration',),
        ),
        migrations.AlterUniqueTogether(
            name='seminarregistration',
            unique_together={('seminar', 'user')},
        ),
        migrations.AddIndex(
            model_name='rankingtransaction',
            index=models.Index(fields=['competition', 'subject_type', 'subject_id'], name='competition_competi_a5485b_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingtransaction',
            index=models.Index(fields=['result'], name='competition_result__adf0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['competition', 'status'], name='competition_competi_9529e9_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['coach'], name='competition_coach_i_57664e_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['club'], name='competition_club_id_cbd6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['board'], name='competition_board_i_552d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['competition', 'player'], name='competition_competi_87726b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poomsaeenrollment',
            unique_together={('competition', 'player', 'poomsae_type')},
        ),
        migrations.AddIndex(
            model_name='poomsaedivision',
            index=models.Index(fields=['competition', 'age_category', 'belt_group', 'style'], name='competition_competi_d067e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poomsaedivision',
            unique_together={('competition', 'age_category', 'belt_group', 'style')},
        ),
        migrations.AddIndex(
            model_name='poomsaecompetition',
            index=models.Index(fields=['public_id'], name='competition_public__3b1384_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaecompetition',
            index=models.Index(fields=['start_date'], name='competition_start_d_b4b3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaecompetition',
            index=models.Index(fields=['registration_start', 'registration_end'], name='competition_registr_1718e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='poomsaecompetition',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='poomsae_start_lte_end'),
        ),
        migrations.AddConstraint(
            model_name='poomsaecompetition',
            constraint=models.CheckConstraint(check=models.Q(('registration_start__lte', models.F('registration_end'))), name='poomsae_reg_start_lte_end'),
        ),
        migrations.AddConstraint(
            model_name='poomsaecompetition',
            constraint=models.CheckConstraint(check=models.Q(('registration_end__lte', models.F('start_date'))), name='poomsae_reg_end_lte_start_date'),
        ),
        migrations.AddIndex(
            model_name='poomsaecoachapproval',
            index=models.Index(fields=['competition', 'is_active', 'approved'], name='competition_competi_772bb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='poomsaecoachapproval',
            constraint=models.UniqueConstraint(fields=('competition', 'coach'), name='uniq_poomsae_competition_coach'),
        ),
        migrations.AddConstraint(
            model_name='poomsaecoachapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('competition', 'code'), name='uniq_poomsae_competition_code'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['draw', 'round_no'], name='competition_draw_id_bc410e_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['mat_no', 'match_number'], name='competition_mat_no_fb64cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kyorugiresult',
            unique_together={('competition', 'weight_category')},
        ),
        migrations.AddIndex(
            model_name='kyorugicompetition',
            index=models.Index(fields=['public_id'], name='competition_public__f756e4_idx'),
        ),
        migrations.AddIndex(
            model_name='kyorugicompetition',
            index=models.Index(fields=['competition_date'], name='competition_competi_cafbd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='kyorugicompetition',
            constraint=models.CheckConstraint(check=models.Q(('registration_start__lte', models.F('registration_end'))), name='reg_start_lte_reg_end'),
        ),
        migrations.AddConstraint(
            model_name='kyorugicompetition',
            constraint=models.CheckConstraint(check=models.Q(('weigh_date__lte', models.F('draw_date'))), name='weigh_lte_draw'),
        ),
        migrations.AddConstraint(
            model_name='kyorugicompetition',
            constraint=models.CheckConstraint(check=models.Q(('draw_date__lte', models.F('competition_date'))), name='draw_lte_comp'),
        ),
        migrations.AlterUniqueTogether(
            name='firstroundpairhistory',
            unique_together={('player_a', 'player_b', 'gender', 'age_category', 'belt_group', 'weight_category')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['competition', 'status'], name='competition_competi_e9adb2_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['coach'], name='competition_coach_i_e3c33b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['club'], name='competition_club_id_a81a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['board'], name='competition_board_i_f2dec0_idx'),
        ),
        migrations.AddIndex(
            model_name='draw',
            index=models.Index(fields=['competition', 'gender', 'age_category', 'belt_group', 'weight_category'], name='competition_competi_9305f8_idx'),
        ),
        migrations.AddIndex(
            model_name='draw',
            index=models.Index(fields=['competition', 'weight_category'], name='competition_competi_21ffac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='draw',
            unique_together={('competition', 'gender', 'age_category', 'belt_group', 'weight_category')},
        ),
        migrations.AddIndex(
            model_name='coachapproval',
            index=models.Index(fields=['competition', 'is_active', 'terms_accepted'], name='competition_competi_30ddd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachapproval',
            constraint=models.UniqueConstraint(fields=('competition', 'coach'), name='uniq_competition_coach'),
        ),
        migrations.AddConstraint(
            model_name='coachapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('competition', 'code'), name='uniq_competition_code'),
        ),
    ]
