# Generated by Django 4.2.13 on 2025-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='discount_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='discount_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payable_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='discount_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='discount_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='payable_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف (تومان)'),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='discount_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='discount_redeemed',
            field=models.BooleanField(default=False, verbose_name='تخفیف مصرف\u200cشده؟'),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='payable_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ نهایی قابل پرداخت (تومان)'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['discount_code'], name='competition_discoun_74bb7f_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['discount_code'], name='competition_discoun_97adcd_idx'),
        ),
    ]
