# Generated by Django 4.2 on 2025-11-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_enrollment_discount_amount_enrollment_discount_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poomsaecompetition',
            name='registration_end',
            field=models.DateField(verbose_name='پایان ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='poomsaecompetition',
            name='registration_start',
            field=models.DateField(verbose_name='شروع ثبت\u200cنام'),
        ),
    ]
