# Generated by Django 4.2.13 on 2025-11-30 13:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0003_alter_poomsaecompetition_registration_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثلاً: CHB2025-ALICOACH', max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('type', models.CharField(choices=[('COACH_GROUP', 'تخفیف مربی (گروهی)'), ('STUDENT', 'تخفیف هنرجو (تکی)')], max_length=20, verbose_name='نوع کد')),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='فقط برای کد هنرجو. اگر خالی باشد یعنی نامحدود.', null=True, verbose_name='حداکثر تعداد استفاده (برای هنرجو)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده\u200cشده')),
                ('active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to=settings.AUTH_USER_MODEL, verbose_name='مربی')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='competitions.kyorugicompetition', verbose_name='مسابقه')),
                ('seminar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='competitions.seminar', verbose_name='سمینار')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
    ]
