# Generated by Django 4.2.13 on 2025-12-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='poomsae_competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes_poomsae', to='competitions.poomsaecompetition', verbose_name='مسابقه پومسه'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='competitions.kyorugicompetition', verbose_name='مسابقه کیوروگی'),
        ),
    ]
