# Generated by Django 4.2.13 on 2025-12-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_pendingclub_license_image_and_more'),
        ('competitions', '0005_discountcode_poomsae_competition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoomsaeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تیم')),
                ('style', models.CharField(choices=[('standard', 'استاندارد'), ('creative', 'ابداعی')], max_length=16, verbose_name='سبک تیم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='poomsae_teams', to='accounts.userprofile', verbose_name='مربی')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.poomsaecompetition', verbose_name='مسابقه پومسه')),
            ],
            options={
                'verbose_name': 'تیم پومسه',
                'verbose_name_plural': 'تیم\u200cهای پومسه',
            },
        ),
        migrations.AlterUniqueTogether(
            name='poomsaeenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='mode',
            field=models.CharField(choices=[('single', 'انفرادی'), ('team', 'تیمی')], default='single', max_length=8, verbose_name='نحوه شرکت'),
        ),
        migrations.AlterUniqueTogether(
            name='poomsaeenrollment',
            unique_together={('competition', 'player', 'poomsae_type', 'mode')},
        ),
        migrations.CreateModel(
            name='PoomsaeTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'اصلی'), ('sub', 'ذخیره')], default='main', max_length=8, verbose_name='نقش در تیم')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='برای مرتب\u200cکردن اعضا (۱، ۲، ۳، ...)', verbose_name='ترتیب در تیم')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poomsae_team_memberships', to='accounts.userprofile', verbose_name='بازیکن')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='competitions.poomsaeteam', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'عضو تیم پومسه',
                'verbose_name_plural': 'اعضای تیم\u200cهای پومسه',
                'indexes': [models.Index(fields=['team'], name='competition_team_id_e1a22e_idx'), models.Index(fields=['player'], name='competition_player__0e271a_idx')],
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.AddIndex(
            model_name='poomsaeteam',
            index=models.Index(fields=['competition', 'coach'], name='competition_competi_9d6569_idx'),
        ),
    ]
