# Generated by Django 4.2.13 on 2025-12-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_poomsaeteam_alter_poomsaeenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poomsaeenrollment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='competitions.poomsaeteam', verbose_name='تیم'),
        ),
    ]
