# Generated by Django 4.2.13 on 2025-12-16 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pendingeditprofile_profile_image_and_more'),
        ('competitions', '0007_poomsaeenrollment_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poomsaeenrollment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='poomsaeenrollment',
            name='competition_competi_9529e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='poomsaeenrollment',
            name='competition_coach_i_57664e_idx',
        ),
        migrations.RemoveIndex(
            model_name='poomsaeenrollment',
            name='competition_club_id_cbd6c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='poomsaeenrollment',
            name='competition_board_i_552d0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='poomsaeenrollment',
            name='competition_competi_87726b_idx',
        ),
        migrations.RemoveIndex(
            model_name='poomsaeenrollment',
            name='competition_discoun_97adcd_idx',
        ),
        migrations.RemoveField(
            model_name='poomsaeenrollment',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='poomsaeenrollment',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='poomsaeenrollment',
            name='discount_redeemed',
        ),
        migrations.RemoveField(
            model_name='poomsaeenrollment',
            name='medal',
        ),
        migrations.RemoveField(
            model_name='poomsaeenrollment',
            name='payable_amount',
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.agecategory'),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='bank_ref_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='belt_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.beltgroup'),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tkdboard'),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='board_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tkdclub'),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='club_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_coach_enrollments', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='coach_approval_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='coach_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='competitions.poomsaecompetition'),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='insurance_issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='insurance_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='mode',
            field=models.CharField(choices=[('single', 'انفرادی'), ('team', 'تیمی')], default='single', max_length=8),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poomsae_enrollments', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='poomsae_type',
            field=models.CharField(choices=[('standard', 'استاندارد'), ('creative', 'ابداعی')], max_length=16),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='status',
            field=models.CharField(default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='competitions.poomsaeteam'),
        ),
    ]
