# Generated by Django 4.2.13 on 2025-12-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pendingeditprofile_profile_image_and_more'),
        ('competitions', '0008_alter_poomsaeenrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poomsaeenrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='poomsaeenrollment',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poomsae_enrollments', to='accounts.userprofile'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['competition', 'mode', 'poomsae_type'], name='competition_competi_3355ce_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['competition', 'player'], name='competition_competi_87726b_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['competition', 'team'], name='competition_competi_a8abbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='poomsaeenrollment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mode', 'single'), ('player__isnull', False), ('team__isnull', True)), models.Q(('mode', 'team'), ('player__isnull', True), ('team__isnull', False)), _connector='OR'), name='poomsae_enrollment_mode_requires_player_or_team'),
        ),
        migrations.AddConstraint(
            model_name='poomsaeenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'single')), fields=('competition', 'player', 'poomsae_type'), name='uniq_poomsae_single_per_style'),
        ),
        migrations.AddConstraint(
            model_name='poomsaeenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'team')), fields=('competition', 'team'), name='uniq_poomsae_team_once'),
        ),
    ]
