# Generated by Django 4.2.13 on 2025-12-28 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_poomsaeenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poomsaecompetition',
            name='mat_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد زمین'),
        ),
        migrations.CreateModel(
            name='PoomsaeMatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_number', models.PositiveIntegerField(verbose_name='شماره زمین')),
                ('belt_groups', models.ManyToManyField(blank=True, related_name='poomsae_mat_assignments', to='competitions.beltgroup', verbose_name='گروه\u200cهای کمربندی تخصیص\u200cیافته')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_assignments', to='competitions.poomsaecompetition', verbose_name='مسابقه پومسه')),
            ],
            options={
                'verbose_name': 'تخصیص زمین پومسه',
                'verbose_name_plural': 'تخصیص رده\u200cهای کمربندی به زمین\u200cهای پومسه',
                'indexes': [models.Index(fields=['competition', 'mat_number'], name='competition_competi_c2e903_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='poomsaematassignment',
            constraint=models.UniqueConstraint(fields=('competition', 'mat_number'), name='uniq_poomsae_mat_per_competition'),
        ),
    ]
