# Generated by Django 4.2.13 on 2026-01-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pendingeditprofile_profile_image_and_more'),
        ('competitions', '0010_poomsaecompetition_mat_count_poomsaematassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRegistrationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('total_amount', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('bank_ref_code', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_payments', to='accounts.userprofile')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_payments', to='competitions.kyorugicompetition')),
            ],
        ),
    ]
