# Generated by Django 4.2.13 on 2026-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_groupregistrationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollments_created',
            field=models.BooleanField(default=False),
        ),
    ]
