# Generated by Django 4.2.13 on 2026-01-29 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_enrollment_enrollments_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarregistration',
            name='bank_ref_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='کد رهگیری بانک'),
        ),
        migrations.AlterField(
            model_name='kyorugicompetition',
            name='entry_fee',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ ورودی (ریال)'),
        ),
        migrations.AlterField(
            model_name='poomsaecompetition',
            name='entry_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه ورودی (ریال)'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='fee',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه (ریال)'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف (ریال)'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداختی (ریال)'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='payable_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ نهایی قابل پرداخت (ریال)'),
        ),
    ]
